### ISSUE TITLE
[Update] 09월 05일 회의 내용 정리

### ISSUE THREAD

**Issue by mnxmnz** [th0532/Readme#1]
2020-2 종합프로젝트

README

프로젝트 개요

- AS-IS
   - 학생회의 공약 이행이 원활하게 수행되고 있는지 시각적으로 확인할 수 있는 사이트가 없음
   - 학생회의 공지사항을 한 곳에 모은 사이트가 없어서 공지를 놓치기 쉬움
   - 코로나로 인해 오프라인으로 선거 운동을 할 수 없어서 선거 운동에 어려움을 겪음

- TO-BE
   - 이행 예정 공약, 이행 완료 공약 및 공약 실천 과정 사진 등 학생회의 공약 실천 현황을 시각적으로 확인할 수 있음
   - 모든 학생회의 공지사항을 언제 어디서나 확인할 수 있음 
   - 사이트에 투표 팸플릿 및 목표 공약을 등록하여 온라인으로 선거를 독려할 수 있음

- GOAL
   - 학생회는 공약을 성실히 수행하여 학교 발전과 재학생을 위해 더욱 노력함
   - 학생회의 공지사항을 확인하고 재학생이 학교 행사에 적극적으로 참여하여 학생회와 재학생이 원활하게 소통할 수 있음
   - 언제 어디서나 학생회 투표 관련 정보를 확인할 수 있게 하여 재학생의 투표에 대한 관심도를 높임
 

활용기술

- FRONT-END
   - React

- BACK-END
   - Node.js
   - Express

- DB
   - MySQL

- Tool
   - Git
   - Slack

역할

- 이태희: Full-Stack
- 변건오: Back-End
- 김민지: Front-End
 

화면구성

1차 구현 목표 

- 로그인 화면
   - 회원가입
   - 로그인, 로그아웃 (네이버, 페이스북 로그인 API)
   - 마이 페이지
   - 관리자 페이지

- 선거
   - 학생회 공약 (총학생회, 단과대 학과 분리)
   - 투표 결과 (그래프)
   - 현재 투표율 (그래프)

- 학생회 공약
   - 현재 진행중인 공약 (막대 그래프) (학생회는 사진 추가할 수 있음)
   - 진행 예정인 공약
   - 진행 완료된 공약

**Comment by mnxmnz** [comment]
제가 기억나는 내용 최대한 적었는데 수정할 사항 있으면 편하게 수정해주세요! 단톡으로 말씀해 주셔도 괜찮아요!

**Comment by th0532** [comment]
늦은시간까지 너무 고생많으셨어요!

+ 온라인 투표라는 문제점을 생각해봤는데
신원 확인에 어려움에 있어 다시한번 고민해보는게
좋을거같아요
투표 기능에 어려움이 있다고 판단되면 투표 기능은 빼고
기존처럼 공약과, 결과만 하는것이 좋아보입니다!
추가로 데이터 입력하면 막대 차트로 현재 투표율도 표출해주면 좋을꺼같아요! 저희 학교 투표를 보면 담당자들만 투표율을 알 수있고 학생들은알 수있는 시스템이 아니라서
이런 기능이 있으면 좋을꺼 같아요!

**Comment by th0532** [comment]
민지씨가 말한 bcrypt 같은 경우는! 복호화 암호화 인것으로 알구있어요! 어제 말한 회원가입할때 db에 저장될때 값을 해싱해서 저장하는건데
제가 생각되는 문제는! 투표자의 신원 확인이 확실히 될 수가없어서 
대리 투표라던가 중복투표 같은 문제가 있을거같아요!
이 문제는 교수님과 논의해보는게 좋을거 같습니다!

**Comment by mnxmnz** [comment]
네 감사합니다! ㅎㅎ

그러면 교수님께서 확인하신 이후에 다시 얘기해봐야겠지만

일단 공약 + 결과 추가로 현재 투표율 이렇게 생각하고 있을게요!
